# -*- coding: utf-8 -*-
"""Hackathon_Yolo_Edition2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7Jr_hR7wT7yiCC_GNT-bRjwKBEdGnhy
"""



"""Connecting With T4


"""

# CELL 1 — Mount Drive + Check GPU
from google.colab import drive
drive.mount('/content/drive')

import torch

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("CUDA is not available. Please ensure you are running a GPU runtime.")

"""Installing Libraries"""

!pip install -q timm albumentations segmentation-models-pytorch
print("✅ Done!")

"""Extracting the Path

### Action Required: Update `zip_path`

The previous cell failed because the zip file `Offroad_Segmentation_Training_Dataset.zip` was not found at the specified path: `/content/drive/MyDrive/Offroad_Segmentation_Training_Dataset.zip`.

**Please do the following:**
1.  **Verify the location** of your `Offroad_Segmentation_Training_Dataset.zip` file in your Google Drive.
2.  **Update the `zip_path` variable** in the code cell below (`e1NSSssKitOO`) with the correct, full path to your zip file.
3.  **Re-run** the code cell `e1NSSssKitOO`.
"""

import zipfile, os

# Fixed path — zip is inside your dataset folder
zip_path = "/content/drive/MyDrive/duality_hackathon/dataset/Offroad_Segmentation_Training_Dataset.zip"
extract_path = "/content/dataset"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(extract_path)

# Show structure
for root, dirs, files in os.walk(extract_path):
    depth = root.replace(extract_path, '').count(os.sep)
    if depth > 2: continue
    print('  ' * depth + os.path.basename(root) + '/')
    if depth == 2:
        print('  ' * (depth+1) + f"... {len(files)} files")

print("✅ Unzip done!")

import os

extract_path = "/content/dataset"

# Scan all levels deep
for root, dirs, files in os.walk(extract_path):
    depth = root.replace(extract_path, '').count(os.sep)
    indent = '  ' * depth
    print(f"{indent}{os.path.basename(root)}/")
    if files:
        print(f"{'  ' * (depth+1)}... {len(files)} files  |  sample: {files[0]}")

"""Training"""

import os, numpy as np, cv2
from PIL import Image
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
import albumentations as A
from albumentations.pytorch import ToTensorV2
import segmentation_models_pytorch as smp
import matplotlib.pyplot as plt

device = torch.device("cuda")
print(f"✅ Device: {torch.cuda.get_device_name(0)}")

CLASS_MAP = {100:0, 200:1, 300:2, 500:3, 550:4, 600:5, 700:6, 800:7, 7100:8, 10000:9}
CLASS_NAMES = ['Trees','Lush Bushes','Dry Grass','Dry Bushes','Ground Clutter',
               'Flowers','Logs','Rocks','Landscape','Sky']
NUM_CLASSES = 10
IGNORE_LABEL = 255

def remap_mask(mask_np):
    out = np.full_like(mask_np, IGNORE_LABEL, dtype=np.uint8)
    for raw, new in CLASS_MAP.items():
        out[mask_np == raw] = new
    return out

print("✅ Imports done!")

IMG_SIZE = 504

TRAIN_TRANSFORMS = A.Compose([
    A.RandomCrop(IMG_SIZE, IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.ShiftScaleRotate(shift_limit=0.1, scale_limit=0.2,
                       rotate_limit=15, p=0.5),
    A.RandomBrightnessContrast(p=0.4),
    A.HueSaturationValue(p=0.3),
    A.GaussNoise(var_limit=(10,50), p=0.2),
    A.GridDistortion(p=0.2),
    A.CoarseDropout(num_holes_range=(1,8),
                    hole_height_range=(16,32),
                    hole_width_range=(16,32), p=0.3),
    A.Normalize(mean=(0.485,0.456,0.406), std=(0.229,0.224,0.225)),
    ToTensorV2(),
])

VAL_TRANSFORMS = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.Normalize(mean=(0.485,0.456,0.406), std=(0.229,0.224,0.225)),
    ToTensorV2(),
])

A.Affine(translate_percent=0.1, scale=(0.8,1.2), rotate=(-15,15), p=0.5),
A.GaussNoise(p=0.2),

class OffRoadDataset(Dataset):
    def __init__(self, img_dir, mask_dir, transforms):
        self.img_dir    = img_dir
        self.mask_dir   = mask_dir
        self.transforms = transforms
        self.images     = sorted(os.listdir(img_dir))

    def __len__(self): return len(self.images)

    def __getitem__(self, idx):
        fname = self.images[idx]
        img   = np.array(Image.open(
                    os.path.join(self.img_dir, fname)).convert('RGB'))
        mask_path = os.path.join(self.mask_dir, fname)
        if not os.path.exists(mask_path):
            base = os.path.splitext(fname)[0]
            mask_path = os.path.join(self.mask_dir, base + '.png')
        mask = np.array(Image.open(mask_path))
        if mask.ndim == 3: mask = mask[..., 0]
        mask = remap_mask(mask)
        aug  = self.transforms(image=img, mask=mask)
        return aug['image'], aug['mask'].long()

BASE          = "/content/dataset/Offroad_Segmentation_Training_Dataset"
TRAIN_IMG_DIR = f"{BASE}/train/Color_Images"
TRAIN_MSK_DIR = f"{BASE}/train/Segmentation"
VAL_IMG_DIR   = f"{BASE}/val/Color_Images"
VAL_MSK_DIR   = f"{BASE}/val/Segmentation"

train_ds = OffRoadDataset(TRAIN_IMG_DIR, TRAIN_MSK_DIR, TRAIN_TRANSFORMS)
val_ds   = OffRoadDataset(VAL_IMG_DIR,   VAL_MSK_DIR,   VAL_TRANSFORMS)

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True,
                          num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=4, shuffle=False,
                          num_workers=2, pin_memory=True)

print(f"✅ Train: {len(train_ds)} images | Val: {len(val_ds)} images")
print(f"   Train batches: {len(train_loader)} | Val batches: {len(val_loader)}")

print("Computing class weights (takes ~1 min)...")
counts = np.zeros(NUM_CLASSES, dtype=np.float64)
mask_files = [os.path.join(TRAIN_MSK_DIR, f)
              for f in os.listdir(TRAIN_MSK_DIR)
              if f.lower().endswith(('.png','.jpg'))]

for mf in mask_files:
    m = np.array(Image.open(mf))
    if m.ndim == 3: m = m[..., 0]
    m = remap_mask(m)
    for c in range(NUM_CLASSES):
        counts[c] += (m == c).sum()

counts  = np.where(counts == 0, 1, counts)
weights = 1.0 / counts
weights = weights / weights.sum() * NUM_CLASSES
class_weights = torch.tensor(weights, dtype=torch.float32).to(device)

print(f"\n{'Class':<18} {'Pixels':>14} {'Weight':>10}")
print("-" * 44)
for i,(n,c,w) in enumerate(zip(CLASS_NAMES, counts, weights)):
    print(f"{n:<18} {int(c):>14,} {w:>10.4f}")
print("\n✅ Class weights ready!")

"""CELL 6 — Model"""

class DINOv2SegModel(nn.Module):
    def __init__(self, num_classes=NUM_CLASSES):
        super().__init__()
        self.backbone = torch.hub.load(
            'facebookresearch/dinov2', 'dinov2_vits14')
        for p in self.backbone.parameters():
            p.requires_grad = False

        self.head = nn.Sequential(
            nn.ConvTranspose2d(384, 256, kernel_size=2, stride=2),
            nn.BatchNorm2d(256), nn.GELU(),
            nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2),
            nn.BatchNorm2d(128), nn.GELU(),
            nn.ConvTranspose2d(128, 64,  kernel_size=2, stride=2),
            nn.BatchNorm2d(64),  nn.GELU(),
            nn.Conv2d(64, num_classes, kernel_size=1),
        )

    def forward(self, x):
        H, W = x.shape[2], x.shape[3]
        with torch.no_grad():
            tokens = self.backbone.get_intermediate_layers(x, n=1)[0]
        B, N, C = tokens.shape
        g    = int(N ** 0.5)
        feat = tokens.permute(0,2,1).reshape(B, C, g, g)
        logits = self.head(feat)
        return F.interpolate(logits, size=(H,W),
                             mode='bilinear', align_corners=False)

model = DINOv2SegModel().to(device)
total     = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"✅ Model ready | Total: {total:,} | Trainable: {trainable:,} | Frozen: {total-trainable:,}")

ce_loss   = nn.CrossEntropyLoss(weight=class_weights, ignore_index=255)
dice_loss = smp.losses.DiceLoss(mode='multiclass', ignore_index=255)

def criterion(logits, masks):
    return 0.6 * ce_loss(logits, masks) + 0.4 * dice_loss(logits, masks)

optimizer = AdamW(model.head.parameters(), lr=3e-4, weight_decay=1e-2)
scheduler = CosineAnnealingLR(optimizer, T_max=50, eta_min=1e-6)

print("✅ Loss + Optimizer ready!")

def compute_iou(preds, masks, num_classes=NUM_CLASSES):
    preds = preds.cpu().numpy()
    masks = masks.cpu().numpy()
    per_class, valid = [], []
    for c in range(num_classes):
        gt_c  = (masks == c) & (masks != 255)
        pr_c  = (preds == c) & (masks != 255)
        inter = (gt_c & pr_c).sum()
        union = (gt_c | pr_c).sum()
        if union == 0:
            per_class.append(None)
        else:
            iou = inter / union
            per_class.append(iou)
            valid.append(iou)
    return float(np.mean(valid)) if valid else 0.0, per_class

print("✅ IoU function ready!")

"""CELL 9 — Training Loop (THE BIG ONE)"""

SAVE_DIR = "/content/drive/MyDrive/duality_hackathon/weights"
PLOT_DIR = "/content/drive/MyDrive/duality_hackathon/runs"
os.makedirs(SAVE_DIR, exist_ok=True)
os.makedirs(PLOT_DIR, exist_ok=True)

EPOCHS    = 50
history   = {"train_loss":[], "val_loss":[], "val_miou":[]}
best_miou = 0.0
patience  = 10
no_improve = 0

for epoch in range(1, EPOCHS + 1):

    # ── TRAIN ──────────────────────────────────────────
    model.train()
    train_loss = 0.0
    for batch_idx, (imgs, masks) in enumerate(train_loader, 1):
        imgs, masks = imgs.to(device), masks.to(device)
        optimizer.zero_grad()
        logits = model(imgs)
        loss   = criterion(logits, masks)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
        print(f"\rEpoch {epoch}/{EPOCHS} | Batch {batch_idx}/{len(train_loader)} "
              f"| Loss: {loss.item():.4f}", end="", flush=True)

    train_loss /= len(train_loader)
    print()

    # ── UNFREEZE last 2 blocks at epoch 20 ─────────────
    if epoch == 20:
        for name, param in model.backbone.named_parameters():
            if 'blocks.10' in name or 'blocks.11' in name:
                param.requires_grad = True
        optimizer.add_param_group({
            'params': [p for n,p in model.backbone.named_parameters()
                       if p.requires_grad],
            'lr': 1e-5
        })
        print("🔓 Backbone last 2 blocks unfrozen!")

    # ── VALIDATE ───────────────────────────────────────
    model.eval()
    val_loss, all_preds, all_masks = 0.0, [], []
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(device), masks.to(device)
            logits = model(imgs)
            val_loss += criterion(logits, masks).item()
            all_preds.append(logits.argmax(dim=1).cpu())
            all_masks.append(masks.cpu())

    val_loss /= len(val_loader)
    miou, per_class = compute_iou(
        torch.cat(all_preds), torch.cat(all_masks))

    scheduler.step()
    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["val_miou"].append(miou)

    # ── SAVE BEST ──────────────────────────────────────
    saved = ""
    if miou > best_miou:
        best_miou = miou
        no_improve = 0
        torch.save(model.state_dict(),
                   f"{SAVE_DIR}/best_model.pth")
        saved = " ✅ saved"
    else:
        no_improve += 1

    print(f"Epoch {epoch}/{EPOCHS} | "
          f"Train: {train_loss:.4f} | "
          f"Val: {val_loss:.4f} | "
          f"mIoU: {miou:.4f} | "
          f"Best: {best_miou:.4f}{saved}")

    # ── PER CLASS every 5 epochs ───────────────────────
    if epoch % 5 == 0:
        print("\n  Per-class IoU:")
        for i,(name,iou) in enumerate(zip(CLASS_NAMES, per_class)):
            bar = "⚠️" if (iou and iou < 0.45) else "✅"
            val = f"{iou:.3f}" if iou else "N/A"
            print(f"    {bar} {name:<18} {val}")
        print()

    # ── EARLY STOP ─────────────────────────────────────
    if no_improve >= patience:
        print(f"⏹ Early stop at epoch {epoch}. Best mIoU: {best_miou:.4f}")
        break

print(f"\n🏆 Training complete! Best mIoU: {best_miou:.4f}")

WEIGHTS_PATH = "/content/drive/MyDrive/duality_hackathon/weights/best_model.pth"
model = DINOv2SegModel().to(device)
model.load_state_dict(torch.load(WEIGHTS_PATH, map_location=device))
model.eval()
print("✅ Model loaded!")

# Ye cell training ke baad use hoga — abhi ready kar lo
# Sirf paste karo, run mat karo abhi

# TTA Inference function — ready rakhna
import cv2, os, torch, torch.nn.functional as F
import numpy as np, albumentations as A
from albumentations.pytorch import ToTensorV2
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

def tta_predict(model, img_rgb, device, size=504):
    """6 predictions = original + hflip + 3 scales each with flip"""

    model.eval()
    all_probs = []

    scales = [0.75, 1.0, 1.25]

    for scale in scales:
        h = w = int(size * scale)
        # clamp to safe size for DINOv2 (multiple of 14)
        h = (h // 14) * 14
        w = (w // 14) * 14

        tf = A.Compose([
            A.Resize(h, w),
            A.Normalize(mean=(0.485,0.456,0.406),
                       std=(0.229,0.224,0.225)),
            ToTensorV2()
        ])

        # Original
        t = tf(image=img_rgb)['image'].unsqueeze(0).to(device)
        with torch.no_grad():
            p = F.softmax(model(t), dim=1)
            p = F.interpolate(p, size=(size,size), mode='bilinear',
                            align_corners=False)
        all_probs.append(p.cpu())

        # Horizontal flip
        img_flip = cv2.flip(img_rgb, 1)
        t_f = tf(image=img_flip)['image'].unsqueeze(0).to(device)
        with torch.no_grad():
            p_f = F.softmax(model(t_f), dim=1)
            p_f = F.interpolate(p_f, size=(size,size), mode='bilinear',
                              align_corners=False)
            p_f = p_f.flip(dims=[-1])  # flip back
        all_probs.append(p_f.cpu())

    # Average all 6 predictions
    avg_prob = torch.stack(all_probs).mean(0)
    return avg_prob.argmax(dim=1).squeeze().numpy()

print("✅ TTA function ready — will use after training!")

# Model load karo
WEIGHTS_PATH = "/content/drive/MyDrive/duality_hackathon/weights/best_model.pth"
model = DINOv2SegModel().to(device)
model.load_state_dict(torch.load(WEIGHTS_PATH, map_location=device))
model.eval()
print("✅ Model loaded! mIoU was: 0.4628")

def tta_predict_batch(model, imgs_tensor, device):
    with torch.no_grad():
        p1 = F.softmax(model(imgs_tensor.to(device)), dim=1)
        p2 = F.softmax(model(imgs_tensor.flip(dims=[-1]).to(device)), dim=1)
        p2 = p2.flip(dims=[-1])
    return ((p1 + p2) / 2).argmax(dim=1).cpu()

all_preds, all_masks = [], []
print("Running TTA validation...")
for i, (imgs, masks) in enumerate(val_loader):
    preds = tta_predict_batch(model, imgs, device)
    all_preds.append(preds)
    all_masks.append(masks.cpu())
    if i % 20 == 0:
        print(f"  {i}/{len(val_loader)} done...")

tta_miou, tta_per_class = compute_iou(
    torch.cat(all_preds), torch.cat(all_masks))

print(f"\n{'='*40}")
print(f"  Without TTA : 0.4628")
print(f"  With TTA    : {tta_miou:.4f}")
print(f"  Boost       : +{tta_miou-0.4628:.4f}")
print(f"{'='*40}")
for name, iou in zip(CLASS_NAMES, tta_per_class):
    if iou:
        flag = "✅" if iou >= 0.45 else "⚠️"
        print(f"  {flag} {name:<18} {iou:.3f}")

import zipfile, os

# Pehle dhundo zip kahan hai
for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for f in files:
        if 'test' in f.lower() and f.endswith('.zip'):
            print(f"FOUND: {os.path.join(root, f)}")

# test_zip_path = jo Step 4 mein mila wo path daalo
test_zip_path = "/content/drive/MyDrive/duality_hackathon/dataset/Offroad_Segmentation_testImages.zip"
test_dir = "/content/test_images"
os.makedirs(test_dir, exist_ok=True)

with zipfile.ZipFile(test_zip_path, 'r') as z:
    z.extractall(test_dir)
print("✅ Test images ready!")

# Test files count karo
test_files = [f for f in os.listdir(test_dir)
              if f.lower().endswith(('.png','.jpg'))]
print(f"Total test images: {len(test_files)}")

# Dhundo actual images kahan hain
import os
for root, dirs, files in os.walk("/content/test_images"):
    print(f"Folder: {root}")
    if files:
        print(f"  Files: {len(files)} | Sample: {files[0]}")

# Fix — subfolder se files lo
import glob

# Saari images dhundo chahe kisi bhi subfolder mein hon
test_files = glob.glob("/content/test_images/**/*.png", recursive=True) + \
             glob.glob("/content/test_images/**/*.jpg", recursive=True)

print(f"Total test images found: {len(test_files)}")
if test_files:
    print(f"Sample path: {test_files[0]}")

import zipfile, os, cv2, torch, torch.nn.functional as F
import numpy as np, albumentations as A
from albumentations.pytorch import ToTensorV2
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

def tta_predict(model, img_rgb, device, size=504):
    """6 predictions = original + hflip + 3 scales each with flip"""

    model.eval()
    all_probs = []

    scales = [0.75, 1.0, 1.25]

    for scale in scales:
        h = w = int(size * scale)
        # clamp to safe size for DINOv2 (multiple of 14)
        h = (h // 14) * 14
        w = (w // 14) * 14

        tf = A.Compose([
            A.Resize(h, w),
            A.Normalize(mean=(0.485,0.456,0.406),
                       std=(0.229,0.224,0.225)),
            ToTensorV2()
        ])

        # Original
        t = tf(image=img_rgb)['image'].unsqueeze(0).to(device)
        with torch.no_grad():
            p = F.softmax(model(t), dim=1)
            p = F.interpolate(p, size=(size,size), mode='bilinear',
                            align_corners=False)
        all_probs.append(p.cpu())

        # Horizontal flip
        img_flip = cv2.flip(img_rgb, 1)
        t_f = tf(image=img_flip)['image'].unsqueeze(0).to(device)
        with torch.no_grad():
            p_f = F.softmax(model(t_f), dim=1)
            p_f = F.interpolate(p_f, size=(size,size), mode='bilinear',
                              align_corners=False)
            p_f = p_f.flip(dims=[-1])  # flip back
        all_probs.append(p_f.cpu())

    # Average all 6 predictions
    avg_prob = torch.stack(all_probs).mean(0)
    return avg_prob.argmax(dim=1).squeeze().numpy()

# Correct path set karo
test_img_dir = "/content/test_images/Offroad_Segmentation_testImages/Color_Images"
test_files   = sorted([f for f in os.listdir(test_img_dir)
                       if f.lower().endswith(('.png','.jpg'))])

OUT_DIR  = "/content/drive/MyDrive/duality_hackathon/outputs"
RUNS_DIR = "/content/drive/MyDrive/duality_hackathon/runs"
os.makedirs(OUT_DIR, exist_ok=True)

PALETTE = np.array([
    [34,139,34],[0,200,0],[210,180,140],[139,90,43],[128,128,128],
    [255,105,180],[101,67,33],[169,169,169],[255,200,0],[135,206,235]
])

legend_patches = [
    mpatches.Patch(color=PALETTE[i]/255, label=CLASS_NAMES[i])
    for i in range(NUM_CLASSES)
]

print(f"🚀 Generating predictions for {len(test_files)} images...")
print("This will take ~15-20 mins on T4. Don't close Colab!\n")

for idx, fname in enumerate(test_files):
    img_bgr = cv2.imread(os.path.join(test_img_dir, fname))
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # TTA predict
    pred = tta_predict(model, img_rgb, device)

    # Colorize
    color_mask = np.zeros((*pred.shape, 3), dtype=np.uint8)
    for i, c in enumerate(PALETTE):
        color_mask[pred == i] = c

    # Save side by side
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    ax1.imshow(img_rgb);        ax1.set_title("Original RGB"); ax1.axis('off')
    ax2.imshow(color_mask);     ax2.set_title("Predicted Mask"); ax2.axis('off')
    fig.legend(handles=legend_patches, loc='lower center', ncol=5, fontsize=7)
    plt.suptitle(fname, fontsize=9)
    plt.tight_layout()

    out_name = fname.replace('.jpg','.png').replace('.JPG','.png')
    plt.savefig(os.path.join(OUT_DIR, out_name),
                dpi=100, bbox_inches='tight')
    plt.close()

    # Progress every 100 images
    if (idx+1) % 100 == 0 or (idx+1) == len(test_files):
        print(f"  ✅ {idx+1}/{len(test_files)} done "
              f"({((idx+1)/len(test_files)*100):.0f}%)")

print(f"\n🏆 All predictions saved to Drive/outputs/!")

RUNS_DIR = "/content/drive/MyDrive/duality_hackathon/runs"
os.makedirs(RUNS_DIR, exist_ok=True)

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
ep = range(1, len(history["train_loss"])+1)

axes[0].plot(ep, history["train_loss"], color="steelblue", linewidth=2)
axes[0].set_title("Train Loss", fontweight='bold')
axes[0].set_xlabel("Epoch"); axes[0].grid(True, alpha=0.3)

axes[1].plot(ep, history["val_loss"], color="coral", linewidth=2)
axes[1].set_title("Val Loss", fontweight='bold')
axes[1].set_xlabel("Epoch"); axes[1].grid(True, alpha=0.3)

axes[2].plot(ep, history["val_miou"], color="seagreen", linewidth=2)
axes[2].axhline(y=0.4628, color='red', linestyle='--', label='Best: 0.4628')
axes[2].set_title("Val mIoU", fontweight='bold')
axes[2].set_xlabel("Epoch"); axes[2].legend(); axes[2].grid(True, alpha=0.3)

plt.suptitle("Training Curves | Best mIoU: 0.4628 | TTA: 0.4676",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RUNS_DIR}/training_curves.png", dpi=150)
plt.show()
print("✅ Training curves saved!")

classes = CLASS_NAMES
tta_scores = [0.672, 0.591, 0.606, 0.326, 0.269,
              0.444, 0.059, 0.268, 0.487, 0.955]
colors = ["#22c55e" if s >= 0.45 else "#ef4444" for s in tta_scores]

fig, ax = plt.subplots(figsize=(12, 5))
bars = ax.barh(classes, tta_scores, color=colors, edgecolor='white')
ax.axvline(x=0.45, color='orange', linestyle='--',
           linewidth=2, label='Target: 0.45')
ax.axvline(x=tta_miou, color='blue', linestyle='-',
           linewidth=2, label=f'Mean IoU: {tta_miou:.4f}')

for bar, score in zip(bars, tta_scores):
    ax.text(score + 0.01, bar.get_y() + bar.get_height()/2,
            f'{score:.3f}', va='center', fontsize=10, fontweight='bold')

ax.set_xlabel("IoU Score", fontsize=12)
ax.set_title("Per-Class IoU — DINOv2 Segmentation Model (with TTA)",
             fontsize=13, fontweight='bold')
ax.legend(fontsize=10)
ax.set_xlim(0, 1.1)
plt.tight_layout()
plt.savefig(f"{RUNS_DIR}/per_class_iou.png", dpi=150)
plt.show()
print("✅ Per-class IoU chart saved!")

val_files = sorted(os.listdir(VAL_IMG_DIR))
records   = []

print("Finding failure cases...")
for fname in val_files[:50]:
    img_path  = os.path.join(VAL_IMG_DIR, fname)
    mask_path = os.path.join(VAL_MSK_DIR, fname)
    if not os.path.exists(mask_path):
        base = os.path.splitext(fname)[0]
        mask_path = os.path.join(VAL_MSK_DIR, base+'.png')

    img  = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
    mask = np.array(Image.open(mask_path))
    if mask.ndim == 3: mask = mask[...,0]
    mask_r = cv2.resize(remap_mask(mask), (504,504),
                        interpolation=cv2.INTER_NEAREST)
    pred = tta_predict(model, img, device)
    iou,_ = compute_iou(
        torch.tensor(pred).unsqueeze(0),
        torch.tensor(mask_r).unsqueeze(0))
    records.append((fname, iou, img, mask_r, pred))

records.sort(key=lambda x: x[1])
worst = records[:4]

fig, axes = plt.subplots(4, 3, figsize=(14, 18))
for row,(fname,iou,img,gt,pred) in enumerate(worst):
    color_gt   = np.zeros((*gt.shape,3),   dtype=np.uint8)
    color_pred = np.zeros((*pred.shape,3), dtype=np.uint8)
    for i,c in enumerate(PALETTE):
        color_gt[gt==i]     = c
        color_pred[pred==i] = c

    axes[row,0].imshow(cv2.resize(img,(504,504)))
    axes[row,0].set_title(f"RGB\n{fname[:20]}", fontsize=8)
    axes[row,1].imshow(color_gt)
    axes[row,1].set_title(f"Ground Truth\nmIoU:{iou:.3f}", fontsize=8)
    axes[row,2].imshow(color_pred)
    axes[row,2].set_title("Predicted", fontsize=8)
    for ax in axes[row]: ax.axis('off')

plt.suptitle("Failure Cases — 4 Worst Val Predictions",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RUNS_DIR}/failure_cases.png", dpi=120)
plt.show()
print("✅ Failure cases saved!")

import os

readme = """# Duality AI Offroad Segmentation — Team [0]

## Setup
pip install torch torchvision albumentations segmentation-models-pytorch timm

## Training
python train.py  (or run Hackathon_Yolo_Edition2.ipynb cells 1-9)

## Inference
python test.py   (or run TTA inference cells)

## Model
- Architecture: DINOv2 ViT-S/14 + ConvTranspose2d Head
- Best mIoU: 0.4628 | With TTA: 0.4676
- Trained: 30 epochs (early stop) on Tesla T4

## Results
- Sky: 0.955 | Trees: 0.672 | Dry Grass: 0.606
- Logs: 0.059 (weakest — class imbalance)
- Mean IoU: 0.4676 (with TTA)

## Files
- best_model.pth — trained weights
- Hackathon_Yolo_Edition2.ipynb — full pipeline
- runs/ — training curves + failure cases
- outputs/ — test image predictions
"""

readme_path = "/content/drive/MyDrive/duality_hackathon/README.md"
os.makedirs(os.path.dirname(readme_path), exist_ok=True)
with open(readme_path, "w") as f:
    f.write(readme)
print("✅ README saved!")

import os
from google.colab import files
import shutil

BONUS_DIR = "/content/bonus_images"
os.makedirs(BONUS_DIR, exist_ok=True)

uploaded = files.upload()
for filename in uploaded.keys():
    print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')
# Move uploaded files to the BONUS_DIR
for filename in uploaded.keys():
    shutil.move(filename, os.path.join(BONUS_DIR, filename))
print(f'Files moved to {BONUS_DIR}')

import torch

device = torch.device("cpu")
torch.set_num_threads(2)  # speed optimize
print("Using device:", device)

WEIGHTS_PATH = "/content/drive/MyDrive/duality_hackathon/weights/best_model.pth"

model = DINOv2SegModel().to(device)
state_dict = torch.load(WEIGHTS_PATH, map_location=device)
model.load_state_dict(state_dict)
model.eval()

print("✅ Model loaded successfully")